# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk:
- openjdk8
- oraclejdk11
- openjdk11

cache:
  directories:
  - $HOME/.m2

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту artress@ngs.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
    - artress@ngs.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    CODECOV_TOKEN="4a095373-9538-48e2-920e-11dcb6d3a1d4"